apiVersion: v1
kind: Service
metadata:
 name: icecap-api-service
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: icecap-api


#try different ports, maybe try starting a shell in the0 pod, and use curl
#tomorrow quota: check the container to see if there is a route internally
#then find a way to expose the image to the browser
#also figure out a way to install mongodb in here